// const userNames = [
//     'benhwaet',
//     'lernantino',
//     'orangeuglad',
//     'thalassocrat',
//     'sabulous',
//     'noisome',
//     'bugsbunny',
//     'snoopy123',
//     'bb_wolf',
//     'daffyduck',
//     'porkypig',
//     'elmerfudd',
//     'tweetybird',
//     'roadrunner',
//     'wileecoyote',
//     'foghornleghorn',
//     'marvinthemartian',
//     'speedygonzales',
//     'pepelepew',
//     'yosemite_sam',
//     'grannyB'
// ];

// const emails = [
//         'benhwaet@gmail.com',
//         'lernantino@gmail.com',
//         'orangeuglad@gmail.com',
//         'thalassocrat@gmail.com',
//         'sabulous@gmail.com',
//         'noisome@gmail.com',
//         'bugsbunny@gmail.com',
//         'snoopy123@gmail.com',
//         'bb_wolf@gmail.com',
//         'daffyduck@gmail.com',
//         'porkypig@gmail.com',
//         'elmerfudd@gmail.com',
//         'tweetybird@gmail.com',
//         'roadrunner@gmail.com',
//         'wileecoyote@gmail.com',
//         'foghornleghorn@gmail.com',
//         'marvinthemartian@gmail.com',
//         'speedygonzales@gmail.com',
//         'pepelepew@gmail.com',
//         'yosemite_sam@gmail.com',
//         'grannyBcool@gmail.com'
//     ];

// const friendNames = [
//     'lernantino',
//     'orangeuglad',
//     'thalassocrat',
//     'sabulous',
//     'noisome',
//     'bugsbunny',
//     'snoopy123',
//     'bb_wolf',
//     'daffyduck',
//     'porkypig',
//     'elmerfudd',
//     'tweetybird',
//     'roadrunner',
//     'wileecoyote',
//     'foghornleghorn',
//     'marvinthemartian',
//     'speedygonzales',
//     'pepelepew',
//     'yosemite_sam',
//     'grannyB',
//     'benhwaet',
// ];

// const thoughtText = [
//     'I am the best',
//     'I am the worst',
//     'I like bananas',
//     'I like apples',
//     'Life is like a box of chocolates',
//     'Ahoy hoy is a pirate greeting',
//     'What\'s up doc?',
//     'What is the meaning of life?',
//     'I am a lumberjack and I am okay',
//     'Bugs Bunny is horrible',
//     'Th-th-th-that\'s all folks!',
//     'Shhhhh. Be vewy vewy quiet. I\'m hunting wabbits',
//     'I taught I taw a puddy tat',
//     'meep meep',
//     'I am a super genius',
//     'Well howdy doody',
//     'Oh dear, I think that rabbit has escaped',
//     'Andale andale arriba arriba!',
//     'I am a perverted skunk',
//     'Yeeehaawww! I am a cowboy',
//     'I am a sweet old lady',
// ];

// const reactions = [
//     'I agree',
//     'I disagree',
//     'I like it',
//     'I hate it',
//     'I love it',
//     'I am indifferent',
//     'I am not sure',
//     'I am sure',
//     'This is lame',
//     'Bugs Bunny is *AWESOME*',
//     'A speech impediment is nothing to be ashamed of',
//     '*whispers* The rabbit will outsmart you again',
//     'You did! You did see a puddy tat!',
//     'I am a super duper genius',
//     'I disagree with your statement',
//     'And howdy to you too',
//     'The rabbit will always escape',
//     'I am the fastest mouse in all of Mexico',
//     'LEAVE THAT CAT ALONE!',
//     'I am a rootin tootin cowboy',
//     'I like you blueberry pies!',
// ];

// // Export the functions for use in seed.js
// //module.exports = { userNames, emails, friendNames, thoughtText, reactions };